name = input("Type a name: ")
place = input("Type a place: ")
verb = input("Type a verb: ")
noun = input("Type a noun: ")
print(name+ " went to the "+ place+ " where they "+ verb+ " and bought a "+ noun+ ".")